### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [msloekito/splurty2-app#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by msloekito** [comment]
Added:
<meta name="viewport" content="width=device-width, initial-scale=1">

to .html.erb files. That should fix the issue? Do I need to add them to each one (main, about, etc.) or just to main one (app.html.erb?)

**Comment by kenmazaika** [comment]
You won't need to add it to each file, you should be able to add it in one place in `app/views/layouts/application.html.erb` and it will apply across all files.  You can drop it right here (between 7 & 8).

https://github.com/msloekito/splurty2-app/blob/master/app/views/layouts/application.html.erb#L7
